project:
  type: website
  output-dir: _site

website:
  title: "Adolfo De Unanue"
  site-url: https://unanue.mx
  description: "Machine Learning | Operations Research | Political Economy"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Papers
        href: content/papers/index.qmd
      - text: Posts
        href: content/posts/index.qmd
      - text: Projects
        href: content/projects/index.qmd
    right:
      - icon: github
        href: https://github.com/nanounanue
      - icon: gitlab
        href: https://gitlab.com/nanounanue
  page-footer:
    center: |
      Built with [Quarto](https://quarto.org)

format:
  html:
    theme:
      light: [cosmo, styles/custom.scss]
    toc: true
    toc-location: right
    toc-depth: 3
    fontsize: 18px
    linestretch: 1.5
    code-copy: true
    code-overflow: wrap
    highlight-style: github
